<a href="https://colab.research.google.com/github/anshuls01/Paython-NLP/blob/master/py_NLP_06052019.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
print("Hello World")

Hello World


In [2]:
2+2

4

# Print Add and Multiplication

In [12]:
L1=[2,4,6,8,10]
L2=[1,3,5,7,9]
for x in range(0,5):
  print (L1[x] + L2[x])

for x in range(0,5):
  print (L1[x] * 2)

print (L1 + L2)
print (L1*2)

3
7
11
15
19
4
8
12
16
20
[2, 4, 6, 8, 10, 1, 3, 5, 7, 9]
[2, 4, 6, 8, 10, 2, 4, 6, 8, 10]


In [7]:
x = [1,2]
type(x)


list

In [8]:
x={1,2}
type(x)

set

In [25]:
angles=[0,30,60,90,120,150,180,210,240,270,300,330,360]
angle = list(range(0,361,30))
print (angle)
i1= angle.index(90)
print(i1)
i2=angle.index(270)
print(i2)
i1_rev=len(angle) -1 -angle.index(90)
print (i1_rev)
i2_rev=len(angle) -1 -angle.index(270)
print (i2_rev)
print(angle[i1_rev:i2_rev - 1:-1])

[0, 30, 60, 90, 120, 150, 180, 210, 240, 270, 300, 330, 360]
3
9
9
3
[270, 240, 210, 180, 150, 120, 90]


In [40]:
L1 =  [2,4,6,8,10]
L2=L1
print(L1)
del(L2[3])
# L2.remove(8)
print (L2)
print (L1)
L1 = [2,4,6,8,10]
L2 = L1.copy()
del(L2[3])
# L2.remove(8)
print (L2)
print (L1)
print (L2,L1)
L3 = L1[ : ]
print(L3)
del(L3[3])
print(L3)
print(L1)

[2, 4, 6, 8, 10]
[2, 4, 6, 10]
[2, 4, 6, 10]
[2, 4, 6, 10]
[2, 4, 6, 8, 10]
[2, 4, 6, 10] [2, 4, 6, 8, 10]
[2, 4, 6, 8, 10]
[2, 4, 6, 10]
[2, 4, 6, 8, 10]


Installing Package

In [51]:
import numpy as np
import tensorflow as tf

tup = (1,2,3)
print (tup)
tup = tup + (4,)
print (tup)
del(tup[2])

(1, 2, 3)
(1, 2, 3, 4)


TypeError: ignored

Dictionaries

In [65]:
states={'AP':[1234,'Hyd',False],'Arunachal':[5678,'Itanagar',True],'Bihar':[124434,'Patna',True]}
print (states)
print(states['Bihar'])


states['Telangana'] = [891011,'XYZ',True]
print (states)

{'AP': [1234, 'Hyd', False], 'Arunachal': [5678, 'Itanagar', True], 'Bihar': [124434, 'Patna', True]}
[124434, 'Patna', True]
{'AP': [1234, 'Hyd', False], 'Arunachal': [5678, 'Itanagar', True], 'Bihar': [124434, 'Patna', True], 'Telangana': [891011, 'XYZ', True]}


In [52]:
print (x==1)

False


Functions and Lambda

In [71]:
import numpy as np
def deg_rad(angle):
  pi = 3.14
  return np.round(angle*pi/180)

print(deg_rad(360))

deg_rad_inline=lambda angle,rotate:angle/360*22/7+rotate
deg_rad_inline(30,deg_rad(90))

6.0
2.261904761904762


Loops

In [7]:
import numpy as np
rad_angles = []
q2_angles=[]
for a in [30,60,90]:
  pi = 3.14
  rad_angles.append(a*pi/180)
  q2_angles.append(a+90)
  
print (rad_angles)
print (q2_angles)

[0.5233333333333333, 1.0466666666666666, 1.57]
[120, 150, 180]


In [17]:
planets = ['Mercury', 'Venus', 'Earth', 'Mars', 'Jupiter', 'Saturn', 'Uranus', 'Neptune']
for planet in planets:
  print(planet,end =' ')
  
short_planet = [planet for planet in planets if len(planet)<6]
print (short_planet,end=' ')
loud_short_Planet = [planet.upper() + "!" for planet in planets if len(planet)<6]
print (loud_short_Planet)

Mercury Venus Earth Mars Jupiter Saturn Uranus Neptune ['Venus', 'Earth', 'Mars'] ['VENUS!', 'EARTH!', 'MARS!']


In [46]:
import numpy as np
a = np.array([1,2,3])
b = np.array([[1,2,3],[4,5,6]])
e = np.array([(0,0,0),[1,2,3],(0,0,0)])
c = np.zeros([3,4])
d = np.eye(3)
print(a)
print(b)
# print (e)
# print (c)
# print (d)

print (a.shape)
print (b.shape)
print (len(a))
print (len(b))
# print (b.size)
# print (b.dtype)
# b = b.astype(int)
# b.dtype

[1 2 3]
[[1 2 3]
 [4 5 6]]
(3,)
(2, 3)
3
2


In [62]:
from sklearn import datasets
iris = datasets.load_iris();
# print (iris)

x = iris.data
print(x.shape)
print (x.size)
print (x.ndim)

Xsub = x[100:140,2:4]
print (Xsub)
print (Xsub.shape)
# print (x[139:140])
# print (len(y))

(150, 4)
600
2
[[6.  2.5]
 [5.1 1.9]
 [5.9 2.1]
 [5.6 1.8]
 [5.8 2.2]
 [6.6 2.1]
 [4.5 1.7]
 [6.3 1.8]
 [5.8 1.8]
 [6.1 2.5]
 [5.1 2. ]
 [5.3 1.9]
 [5.5 2.1]
 [5.  2. ]
 [5.1 2.4]
 [5.3 2.3]
 [5.5 1.8]
 [6.7 2.2]
 [6.9 2.3]
 [5.  1.5]
 [5.7 2.3]
 [4.9 2. ]
 [6.7 2. ]
 [4.9 1.8]
 [5.7 2.1]
 [6.  1.8]
 [4.8 1.8]
 [4.9 1.8]
 [5.6 2.1]
 [5.8 1.6]
 [6.1 1.9]
 [6.4 2. ]
 [5.6 2.2]
 [5.1 1.5]
 [5.6 1.4]
 [6.1 2.3]
 [5.6 2.4]
 [5.5 1.8]
 [4.8 1.8]
 [5.4 2.1]]
(40, 2)


Pandas

upload file

In [71]:
from google.colab import files
uploaded = files.upload()

Saving matches.csv to matches (1).csv


In [74]:
import pandas as pd
df = pd.read_csv('matches.csv')
print(df.shape)
print(df.columns)
print (list(df.index)[:10])
df.head()

(577, 18)
Index(['id', 'season', 'city', 'date', 'team1', 'team2', 'toss_winner',
       'toss_decision', 'result', 'dl_applied', 'winner', 'win_by_runs',
       'win_by_wickets', 'player_of_match', 'venue', 'umpire1', 'umpire2',
       'umpire3'],
      dtype='object')
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


id  season        city        date                  team1  \
0   1    2008   Bangalore  2008-04-18  Kolkata Knight Riders   
1   2    2008  Chandigarh  2008-04-19    Chennai Super Kings   
2   3    2008       Delhi  2008-04-19       Rajasthan Royals   
3   4    2008      Mumbai  2008-04-20         Mumbai Indians   
4   5    2008     Kolkata  2008-04-20        Deccan Chargers   

                         team2                  toss_winner toss_decision  \
0  Royal Challengers Bangalore  Royal Challengers Bangalore         field   
1              Kings XI Punjab          Chennai Super Kings           bat   
2             Delhi Daredevils             Rajasthan Royals           bat   
3  Royal Challengers Bangalore               Mumbai Indians           bat   
4        Kolkata Knight Riders              Deccan Chargers           bat   

   result  dl_applied                       winner  win_by_runs  \
0  normal           0        Kolkata Knight Riders          140   
1  normal           0          Chennai Super Kings           33   
2  normal           0             Delhi Daredevils            0   
3  normal           0  Royal Challengers Bangalore            0   
4  normal           0        Kolkata Knight Riders            0   

   win_by_wickets player_of_match                                       venue  \
0               0     BB McCullum                       M Chinnaswamy Stadium   
1               0      MEK Hussey  Punjab Cricket Association Stadium, Mohali   
2               9     MF Maharoof                            Feroz Shah Kotla   
3               5      MV Boucher                            Wankhede Stadium   
4               5       DJ Hussey                                Eden Gardens   

     umpire1         umpire2  umpire3  
0  Asad Rauf     RE Koertzen      NaN  
1  MR Benson      SL Shastri      NaN  
2  Aleem Dar  GA Pratapkumar      NaN  
3   SJ Davis       DJ Harper      NaN  
4  BF Bowden     K Hariharan      NaN